name: Continuous Integration

on: [push, pull_request]

jobs:
  tsc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: ./.github/actions/yarn-cache
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: tsc
        run: yarn tsc
